---
- name: Build and deploy container
  hosts: dockerserver
  vars:
    container_name: "finexo_container"
    image_name: "finexo:latest"
  tasks:
    - name: Start a container
      docker_container:
        image: "{{ image_name }}"
        name: "{{ container_name }}"
        ports:
          "80:80"
        state: started




