---
- name: create docker image
  hosts: dockerserver
  vars:
      image_name: "finexo"
  tasks:
    - name: Build an image
      docker_image:
        name: "{{ image_name }}"
        build:
          path: /home/dockeradmin/Jenkins-Ansible-docker/
        source: build
