---
- name: create docker image
  hosts: all
  become: dockeradmin
  tasks:
    vars:
      image_name: "finexo"
    - name: Build an image
      docker_image:
        name: ${{ image_name }}
        build:
          path: Jenkins-Ansible-Docker/finexo/
        source: build
