---
- name: create docker image
  hosts: dockerserver
  vars:
      image_name: "finexo"
  tasks:
    - name: Login to dockerhub"
      docker_login:
        username: armdevu
        password: maarenu2017
    - name: Build an image
      docker_image:
        name: "{{ image_name }}"
        build:
          path: /home/dockeradmin/Jenkins-Ansible-docker/
        source: build
        push: true
        repository: armdevu/finexo
        tag: 1.1
        
    
