---
- name: create docker image
  hosts: dockerserver
  become_user: dockeradmin
  vars:
      image_name: "finexo"
  tasks:
    - name: Build an image
      docker_image:
        name: "{{ image_name }}"
        build:
          path: ~/Jenkins-Ansible-docker/finexo
        source: build
